version: '3'
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.5.1"
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - data-container:/var/lib/elasticsearch
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    volumes:
      - data-container:/data
  dbserver:
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - ../db_data:/var/lib/mysql

  web_app:
    build: ./
    image: flask_app
    environment:
      - DATABASE_URL
      - SECRET_KEY
      - SQLALCHEMY_TRACK_MODIFICATIONS
      - FLASK_APP
      - FLASK_DEBUG
      - MAIL_SERVER
      - MAIL_PORT
      - MAIL_USERNAME
      - MAIL_PASSWORD
      - MAIL_USE_TLS
      - MAIL_USE_SSL
      - DEBUG
      - TRANSLATE_API_KEY
      - ELASTICSEARCH_URL
      - REDIS_URL
    depends_on:
      - redis
      - elasticsearch
      - dbserver
    ports:
      - "5000:5000"

  rq_worker:
    image: "flask_app"
    environment:
      - DATABASE_URL
      - SECRET_KEY
      - SQLALCHEMY_TRACK_MODIFICATIONS
      - FLASK_APP
      - FLASK_DEBUG
      - MAIL_SERVER
      - MAIL_PORT
      - MAIL_USERNAME
      - MAIL_PASSWORD
      - MAIL_USE_TLS
      - MAIL_USE_SSL
      - DEBUG
      - TRANSLATE_API_KEY
      - ELASTICSEARCH_URL
      - REDIS_URL
    depends_on:
      - redis
      - dbserver
    entrypoint: rq worker -u redis://redis:6379 microblog-tasks

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - dbserver
    ports:
      - "8080:80"
    environment:
      - PMA_HOST
      - PMA_PASSWORD
      - PMA_USER

volumes:
  data-container: