version: '3'
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.5.1"
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - data-container:/var/lib/elasticsearch
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    volumes:
      - data-container:/data

volumes:
  data-container: