"""message read status


Revision ID: 6b66049ce89a
Revises: 21a4ffe44890
Create Date: 2020-01-03 23:07:54.524029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b66049ce89a'
down_revision = '21a4ffe44890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('read_status', sa.Boolean(), nullable=True))
    op.add_column('message', sa.Column('token', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'token')
    op.drop_column('message', 'read_status')
    # ### end Alembic commands ###
